# Generated by Django 5.2.6 on 2025-09-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='', max_length=100)),
                ('website_tagline', models.CharField(default='', max_length=100)),
                ('website_description', models.TextField(default='')),
                ('website_logo', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('website_favicon', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('website_thumbnail', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('website_address', models.CharField(default='www.', max_length=255)),
                ('website_contact_phone', models.CharField(default='', max_length=15)),
                ('website_contact_email', models.EmailField(default='', max_length=254)),
                ('website_office_hour', models.TextField(blank=True, default='Mon-Fri : 10:00 AM - 5:00 PM', null=True)),
            ],
        ),
    ]
