# Generated by Django 5.2.7 on 2025-10-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessprofile', '0002_legallink_quicklink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legallink',
            name='url',
        ),
        migrations.RemoveField(
            model_name='quicklink',
            name='url',
        ),
    ]
