# Generated by Django 5.2.6 on 2025-10-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_image_url_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='base_price',
            new_name='price',
        ),
    ]
