# Generated by Django 5.2.6 on 2025-10-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_base_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
