# Generated by Django 5.2.6 on 2025-10-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_has_variation_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
