# Generated by Django 5.2.7 on 2025-10-11 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.variation'),
        ),
    ]
