# Generated by Django 5.2.7 on 2025-10-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_variation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
